// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwTUWDBS8P6fLo1DyQQk1LcdhgPKDMZz8',
    appId: '1:184964985859:web:486d59f2f08cec9c7f4a36',
    messagingSenderId: '184964985859',
    projectId: 'crud-32297',
    authDomain: 'crud-32297.firebaseapp.com',
    storageBucket: 'crud-32297.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_Y5JFjmzPrTm55CARiem9ixXGtx3oEw',
    appId: '1:184964985859:android:ec8af1c91e0530b97f4a36',
    messagingSenderId: '184964985859',
    projectId: 'crud-32297',
    storageBucket: 'crud-32297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvpL5Ly2VUAqKT1nvGMTTPymlSuCWMWJk',
    appId: '1:184964985859:ios:9843ce773bb9bac77f4a36',
    messagingSenderId: '184964985859',
    projectId: 'crud-32297',
    storageBucket: 'crud-32297.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvpL5Ly2VUAqKT1nvGMTTPymlSuCWMWJk',
    appId: '1:184964985859:ios:9843ce773bb9bac77f4a36',
    messagingSenderId: '184964985859',
    projectId: 'crud-32297',
    storageBucket: 'crud-32297.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwTUWDBS8P6fLo1DyQQk1LcdhgPKDMZz8',
    appId: '1:184964985859:web:3e24af2c74fd79717f4a36',
    messagingSenderId: '184964985859',
    projectId: 'crud-32297',
    authDomain: 'crud-32297.firebaseapp.com',
    storageBucket: 'crud-32297.firebasestorage.app',
  );
}
